version: "3"
services:
  nginx:
    image: nginx:1.23.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker.conf:/etc/nginx/conf.d/docker.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./log/nginx:/var/log/nginx
      - ./logrotate/nginx:/etc/logrotate.d/nginx
    restart: always

